name: ds-catalog-service

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8.6
  - bash
  - pip==20.3.1
  - pandas==1.1.5
  - jq==1.6
  - make==4.2.1

  - pip:
      - -r file:requirements.txt
      - -r file:requirements-dev.txt